# uwsgi
# we are using uwsgi-emporer, therefore we need root as each service is running
# under an own user
uwsgi_emperor_uid: 'root'
uwsgi_emperor_gid: 'root'

# askbot

askbot_domain: ask.supergravity.org
askbot_url: http://ask.supergravity.org
askbot_smtp_default_from: ask@supergravity.org
askbot_name: ask_sglabs
askbot_smtp_subject_prefix: '[ask sg]'
askbot_cache_location: '127.0.0.1:11211'
askbot_uwsgi_socket: '{{askbot_base_dir}}/uwsgi-askbot.socket'
askbot_timezone: 'Europe/Berlin'
askbot_multilang: true
askbot_cache: true
askbot_multilang_langs: ['en', 'de']
askbot_admins:
  - sglabs-admin@poelzi.org

# discourse

discourse_hostname: 'discuss.supergravity.org'
discourse_git_branch: 'master'
discourse_smtp_address: '{{ansible_eth0.ipv4.address}}'
discourse_redis: '{{ansible_eth0.ipv4.address}}'
discourse_db_host: "{{ansible_eth0.ipv4.address}}"
discourse_developer_emails:
  - poelzi@poelzi.org
pg_host: "{{ansible_eth0.ipv4.address}}"

discourse_admins:
    - [['admin', 'admin@supergravity.org', '{{ discourse_admin_pwd | default("admin") }}']]


# dokuwiki config

dokuwiki_plugins:
  mathjax:
    url: 'https://github.com/liffiton/dokuwiki-plugin-mathjax/archive/master.zip'
    move: ['dokuwiki-plugin-mathjax-master', 'mathjax']
  indexmenu:
    url: 'https://github.com/samuelet/indexmenu/archive/master.zip'
    move: ['indexmenu-master', 'indexmenu']
  pagelist:
    url: 'https://github.com/dokufreaks/plugin-pagelist/zipball/master'
    move: ['dokufreaks-plugin-pagelist-*', 'pagelist']
  tag:
    url: 'https://github.com/dokufreaks/plugin-tag/zipball/master'
    move: ['dokufreaks-plugin-tag-*', 'tag']
  include:
    url: 'https://github.com/dokufreaks/plugin-include/zipball/master'
    move: ['dokufreaks-plugin-include-*', 'include']
  mimetex:
    url: 'https://github.com/MichaelGr/dokuwiki-plugin-mimeTeX/zipball/master'
    move: ['MichaelGr-dokuwiki-plugin-mimeTeX-*', 'mimetex']
    install: ['mimetex']
  mathjax:
    url: 'https://github.com/liffiton/dokuwiki-plugin-mathjax/archive/master.zip'
    move: ['dokuwiki-plugin-mathjax-master', 'mathjax']
  oauth:
    url: 'https://github.com/supergravity-org/dokuwiki-plugin-oauth/archive/master.zip'
    move: ['dokuwiki-plugin-oauth-master', 'oauth']
  gitlog:
    url: 'https://github.com/alexwenzel/dokuwiki-plugin-gitlog/archive/master.zip'
    move: ['dokuwiki-plugin-gitlog-master', 'gitlog']
  gitbackend:
    url: 'https://github.com/woolfg/dokuwiki-plugin-gitbacked/archive/master.zip'
    move: ['dokuwiki-plugin-gitbacked-master', 'gitbacked']
    install: ['git']

dokuwiki_settings:
  lang: 'en'
  title: supergravity wiki
  license: 'cc-by-sa'
  allowdebug: 1
  useacl: 1
  authtype: 'oauth'
  superuser: '@admin'
  disableactions: 'register,resendpwd,profile,profile_delete'
  "plugin__oauth__custom-key": '{{ dokuwiki_oauth_key }}'
  "plugin__oauth__custom-secret": '{{ dokuwiki_oauth_secret }}'
  "plugin__oauth__custom-authurl": 'http://supergravity.local:8080/auth/o/authorize/'
  "plugin__oauth__custom-tokenurl": 'http://supergravity.local:8080/auth/o/token/'
  "plugin__oauth__custom-meurl": 'http://supergravity.local:8080/api/v1/me.json'
  "plugin__oauth__custom-mapping": 'user=username name=username mail=email'
  "plugin__oauth__custom-scope": 'read'
  "plugin__oauth__singleService": 'Custom'
  "plugin__oauth__register-login": 1

# wagtail

wagtail_hostname: [blog.supergravity.org, blog.supergravity.local]
wagtail_name: supergravity_main
wagtail_src_path: supergravity_main
wagtail_settings: supergravity_main.settings.local
wagtail_uwsgi_socket: '{{wagtail_base_dir}}/uwsgi.socket'
wagtail_test: true
redis_bind: ['0.0.0.0']
use_ssl: true
ssl_cert: 'supergravity.crt'
ssl_private_key: 'supergravity.key'
ca_cert: 'cacert-class3.pem'

# tendenci config

tendenci_src_root: 'sg_tendenci'
tendenci_domain: supergravity.org
tendenci_smtp_default_from: web@supergravity.org
tendenci_name: sg_web
# tendenci_smtp_subject_prefix: '[ask sg]'
tendenci_cache_location: '127.0.0.1:11211'
tendenci_uwsgi_socket: '{{tendenci_base_dir}}/uwsgi-tendenci.socket'
tendenci_timezone: 'Europe/Berlin'
tendenci_cache: true
tendenci_multilang_langs: ['en', 'de']
tendenci_admins:
  - sglabs-admin@poelzi.org

# postgresql
postgresql_conf:
  listen_addresses: "'*'"
postgresql_pg_hba_conf:
  - "host    all             all             {{ansible_eth0.ipv4.address}}/32                 md5"
  - "{% if ansible_docker0 %}host    all             all             {{ansible_docker0.ipv4.address}}/16              md5{% endif %}"

# nginx

nginx_configs:
  http:
    - server_names_hash_bucket_size 128
    - proxy_headers_hash_bucket_size 128
    - proxy_headers_hash_max_size 1024
  upstream:
    - upstream askbot { server unix://{{askbot_base_dir}}/uwsgi-askbot.socket; }
    # - upstream supergravity_main { server unix://{{wagtail_base_dir}}/uwsgi.socket; }
    - upstream tendenci { server unix://{{tendenci_base_dir}}/uwsgi-tendenci.socket; }
nginx_sites:
  default:
    - listen 80
    - server_name _
    - root "/usr/share/nginx/html"
    - index index.html
  ask:
    - listen 80
    - server_name ask.supergravity.org ask.supergravity.local
    - root "/var/www"
    - location / { uwsgi_pass  askbot; include /etc/nginx/uwsgi_params; }
  ask_ssl:
    - listen 443
    - server_name ask.supergravity.org ask.supergravity.local
    - ssl on
    - ssl_certificate /etc/ssl/certs/supergravity.crt
    - ssl_certificate_key /etc/ssl/private/supergravity.key
    - ssl_session_cache shared:SSL:20m
    - ssl_session_timeout 10m
    - ssl_prefer_server_ciphers on
    - ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5
    - ssl_dhparam /etc/ssl/dhparam.pem
    - ssl_protocols TLSv1.1 TLSv1.2
    - >
      {% if ca_cert %}
      ssl_stapling on;
      ssl_stapling_verify;
      ssl_trusted_certificate /etc/ssl/certs/{{ ca_cert }};
      {% endif %}
    - root "/var/www"
    - location / { uwsgi_pass  askbot; include /etc/nginx/uwsgi_params; }
  tendenci:
     - listen 80
     - server_name supergravity.org www.supergravity.org supergravity.local
     - root "/var/www"
     - access_log {{ tendenci_logs_dir }}/nginx-access.log
     - error_log {{ tendenci_logs_dir }}/nginx-error.log
     - "location /media { autoindex {{ kitchen_run and 'on' or 'off' }}; alias {{ tendenci_base_dir}}/media; }"
     - "location /static { autoindex {{ kitchen_run and 'on' or 'off' }}; alias {{ tendenci_base_dir}}/static; }"
     - "location /themes { autoindex {{ kitchen_run and 'on' or 'off' }}; alias {{ tendenci_base_dir}}/themes; }"
     - location / { uwsgi_pass tendenci; include /etc/nginx/uwsgi_params; }
  discuss:
     - listen 80
     - server_name discuss.supergravity.org discuss.supergravity.local
     - root "/var/www"
     - >
       location / {
        proxy_pass http://localhost:3080/;
        proxy_set_header Host      $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        include /etc/nginx/proxy_params;  }
  wiki:
    - listen 80
    - server_name wiki.supergravity.org wiki.supergravity.local
    - root "/var/www"
    - >
       location / {
        proxy_pass http://localhost:{{ dokuwiki_port}}/;
        proxy_set_header Host      $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        include /etc/nginx/proxy_params;  }
