---
- name: Create the application log folder
  file: path={{ sites_dir }}/{{ project_name }}/gunicorn/
        owner={{ deploy_user }}
        group={{ deploy_user }}
        state=directory
  sudo: no
  tags:
      - gunicorn

- name: Copy/Create the gunicorn script
  template: src=gunicorn.j2
            dest={{ sites_dir }}/{{ project_name }}/gunicorn.conf
            backup=yes
  sudo: no
  tags:
      - gunicorn

- name: Install Supervisor 
  apt: name=supervisor update_cache=yes state=latest
  tags:
      - packages
      - supervisor
      - gunicorn

- name: Deploy the Supervisor Script
  template: src=supervisor.j2
            dest=/etc/supervisor/conf.d/{{ project_name }}.conf
            backup=yes
  tags:
     - gunicorn
     - supervisor
- name: Re-read the Supervisor config files
  command: supervisorctl reread
  tags:
     - gunicorn
     - supervisor

- name: Update Supervisor to add the app in the process group
  command: supervisorctl update
  notify: restart gunicorn 
  tags:
     - gunicorn
     - supervisor
