---
- hosts: www
  sudo: true
  roles:
     - { role: sgbasics }
     - { role: galaxyprojectdotorg.postgresql}
     - { role: tersmitten.redis}
     - { role: askbot,
         tags: ['askbot']}
     - { role: supergravity_main,
         tags: ['supergravity_main']}
     - { role: jdauphant.nginx }

  pre_tasks:
    # - { include: 'roles/supergravity_main/tasks/ssl.yml'}

  vars:
    uwsgi_emperor_uid: 'root'
    uwsgi_emperor_gid: 'root'
    askbot_domain: ask.supergravity.org
    askbot_smtp_default_from: ask@supergravity.org
    askbot_name: ask_sglabs
    askbot_smtp_subject_prefix: '[ask sg]'
    askbot_cache_location: '127.0.0.1:11211'
    askbot_uwsgi_socket: '{{askbot_base_dir}}/uwsgi-askbot.socket'
    askbot_timezone: 'Europe/Berlin'
    askbot_multilang: true
    askbot_cache: true
    askbot_multilang_langs: ['en', 'de']
    askbot_admins:
      - sglabs-admin@poelzi.org
    pg_host: localhost
    wagtail_hostname: [supergravity.org, blog.supergravity.org, supergravity.local]
    wagtail_name: supergravity_main
    wagtail_src_path: supergravity_main
    wagtail_settings: supergravity_main.settings.local
    wagtail_uwsgi_socket: '{{wagtail_base_dir}}/uwsgi.socket'
    wagtail_test: true
    use_ssl: true
    ssl_cert: 'supergravity.crt'
    ssl_private_key: 'supergravity.key'
    ca_cert: 'cacert-class3.pem'
    nginx_configs:
      upstream:
        - upstream askbot { server unix://{{askbot_base_dir}}/uwsgi-askbot.socket; }
        - upstream supergravity_main { server unix://{{wagtail_base_dir}}/uwsgi.socket; }
    nginx_sites:
      default:
        - listen 80
        - server_name _
        - root "/usr/share/nginx/html"
        - index index.html
      ask:
        - listen 80
        - server_name ask.supergravity.org ask.supergravity.local
        - root "/var/www"
        - location / { uwsgi_pass  askbot; include /etc/nginx/uwsgi_params; }
      ask_ssl:
        - listen 443
        - server_name ask.supergravity.org ask.supergravity.local
        - ssl on
        - ssl_certificate /etc/ssl/certs/supergravity.crt
        - ssl_certificate_key /etc/ssl/private/supergravity.key
        - ssl_session_cache shared:SSL:20m
        - ssl_session_timeout 10m
        - ssl_prefer_server_ciphers on
        - ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5
        - ssl_dhparam /etc/ssl/dhparam.pem
        - ssl_protocols TLSv1.1 TLSv1.2
        - ssl_stapling on
        - ssl_stapling_verify on
        - '{% if ca_cert %}ssl_trusted_certificate /etc/ssl/certs/{{ ca_cert }}{% endif %}'
        - root "/var/www"
        - location / { uwsgi_pass  askbot; include /etc/nginx/uwsgi_params; }
      # www:
      #   - listen 80
      #   - server_name supergravity.org www.supergravity.org supergravity.local
      #   - root "/var/www"
      #   - location / { uwsgi_pass wagtail; include /etc/nginx/uwsgi_params; }
