---
- hosts: www
  sudo: true
  roles:
     - { role: exim,
         tags: ['mail']}
     - { role: sgmail,
         tags: ['mail']}
     - { role: sgbasics,
         tags: ['sgbasics']
       }
     - { role: install-docker}
     - { role: galaxyprojectdotorg.postgresql}
     - { role: tersmitten.redis}
     - { role: dokuwiki,
         tags: ['dokuwiki']}
     - { role: elasticsearch,
         container_name: elasticsearch,
         data_dir: '/var/lib/elasticsearch' }
     - { role: askbot,
         tags: ['askbot']}
     - { role: tendenci,
         tags: ['tendenci']}
     - { role: supergravity_main,
         tags: ['supergravity_main']}
     - { role: discourse,
         tags: ['discourse'],
        }
     - { role: jdauphant.nginx }

  vars_files:
    - "group_vars/mail.yml"
    - "group_vars/web.yml"

  pre_tasks:
    - { include: 'tasks/ssl.yml'}
    # - { include: ''}
