---
# handlers file for discourse

- name: launcher rebuild
  shell: "/var/discourse/launcher rebuild {{discourse_name}}"

- name: launcher bootstrap
  shell: "/var/discourse/launcher bootstrap {{ discourse_name }}"

- name: launcher start
  shell: "/var/discourse/launcher start {{ discourse_name }}"

- name: launcher stop
  shell: "/var/discourse/launcher stop {{ discourse_name }}"

- name: launcher restart
  shell: "/var/discourse/launcher restart {{ discourse_name }}"

- name: launcher destroy
  shell: "/var/discourse/launcher destroy {{ discourse_name }}"
