---
# defaults file for dokuwiki

# dokuwiki instance name
dokuwiki_name: dokuwiki

# port to expose to
dokuwiki_port: 3780

# directory to build doku
dokuwiki_builddir: /srv/{{dokuwiki_name}}
dokuwiki_datadir: '{{ dokuwiki_builddir }}/data'

dokuwiki_plugins:
  mathjax:
    url: 'https://github.com/liffiton/dokuwiki-plugin-mathjax/archive/master.zip'
    move: ['dokuwiki-plugin-mathjax-master', 'mathjax']
  indexmenu:
    url: 'https://github.com/samuelet/indexmenu/archive/master.zip'
    move: ['indexmenu-master', 'indexmenu']
  pagelist:
    url: 'https://github.com/dokufreaks/plugin-pagelist/zipball/master'
    move: ['dokufreaks-plugin-pagelist-*', 'pagelist']
  tag:
    url: 'https://github.com/dokufreaks/plugin-tag/zipball/master'
    move: ['dokufreaks-plugin-tag-*', 'tag']
  include:
    url: 'https://github.com/dokufreaks/plugin-include/zipball/master'
    move: ['dokufreaks-plugin-include-*', 'include']
  mimetex:
    url: 'https://github.com/MichaelGr/dokuwiki-plugin-mimeTeX/zipball/master'
    move: ['MichaelGr-dokuwiki-plugin-mimeTeX-*', 'mimetex']
    install: ['mimetex']
  mathjax:
    url: 'https://github.com/liffiton/dokuwiki-plugin-mathjax/archive/master.zip'
    move: ['dokuwiki-plugin-mathjax-master', 'mathjax']
  oauth:
    url: 'http://github.com/cosmocode/dokuwiki-plugin-oauth/zipball/master'
    move: ['cosmocode-dokuwiki-plugin-oauth-838277f', 'oauth']
  gitlog:
    url: 'https://github.com/alexwenzel/dokuwiki-plugin-gitlog/archive/master.zip'
    move: ['dokuwiki-plugin-gitlog-master', 'gitlog']
  gitbackend:
    url: 'https://github.com/woolfg/dokuwiki-plugin-gitbacked/archive/master.zip'
    move: ['dokuwiki-plugin-gitbacked-master', 'gitbacked']
    install: ['git']
