---

- include: install.yml
  tags:
    - system
    - openssl
    - install
    - openssl-install

- include: config.yml
  tags:
    - system
    - openssl
    - config
    - openssl-config

- include: manage.yml
  tags:
    - system
    - openssl
    - manage
    - openssl-manage
