---
galaxy_info:
  author: The Galaxy Project
  description: Install and manage a PostgreSQL (http://www.postgresql.org/) server.
  company: The Galaxy Project
  license: AFL v3.0
  min_ansible_version: 1.8
  platforms:
  - name: EL
    versions:
    - all
  - name: Fedora
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
  - database
  - database:sql
dependencies: []
