---
- hosts: localhost
  gather_facts: no
  vars_files:
     - ~/public_keys/do/doapi.yml
  tasks:
      - name: Create an new Droplet 
        digital_ocean: >
            state=present
            command=droplet
            name='tickal
            client_id={{ client_id }}
            api_key={{ api_key }}
            size=66
            region=1
            image_id=1505527
            wait_timeout=500
        register: my_droplet
        
      - debug: msg="ID is {{ my_droplet.droplet.name }}"
