---
- include: install.yml tags=install
- include: configure.yml tags=config

- name: collect static media files
  sudo_user: "{{ askbot_user }}"
  django_manage: >
    app_path={{ askbot_base_dir }}
    virtualenv={{ askbot_virtenv_dir }}
    command=collectstatic

- include: database.yml tags=database
- include: spamprotect.yml tags=spamprotect

- include: uwsgi.yml
  when: ansible_os_family == "Gentoo"

- include: uwsgi-debian.yml
  when: ansible_os_family == "Debian"
