- name: create spam update script
  copy: >
    content='#!/bin/bash\n. {{askbot_virtenv_dir}}/bin/activate; cd {{ askbot_base_dir}}; python manage.py sfsupdate'
    dest={{ askbot_base_dir }}/update_spamlist.sh
    owner={{askbot_user}}
    mode=755

- name: setup spamstop cronjob
  cron: >
    name=update_spamlist
    user={{askbot_user}}
    cron_file=update_spamlist
    job={{ askbot_base_dir }}/update_spamlist.sh
    hour=3
    minute=36

- name: run update spamscript
  sudo_user: "{{ askbot_user }}"
  ignore_errors: yes
  when: "{{ kitchen_run }} == False"
  django_manage: >
    app_path={{ askbot_base_dir }}
    virtualenv={{ askbot_virtenv_dir }}
    command=sfsupdate
