---
- name: install packages
  apt: package={{ item }}
  with_items:
    - python-virtualenv
    - python-psycopg2
    - libpq-dev
    - python-dev
    - npm
    - nodejs
    - nodejs-legacy
    - supervisor
  tags: packages

- name: create wagtail group
  group: >
    name={{ wagtail_group }}
    system=yes
  tags: accounts

- name: create wagtail user
  user: >
    name={{ wagtail_user }}
    group={{ wagtail_group }}
    home={{ wagtail_base_dir }}
    createhome=no
    shell=/sbin/nologin
    system=yes
  tags: accounts

- name: prepare base directory
  file: >
    state=directory
    path={{ wagtail_base_dir }}
    owner={{ wagtail_user }}
    group={{ wagtail_group }}
    mode='0755'

- name: copy website to target
  sudo_user: '{{wagtail_user}}'
  synchronize: >
    archive=no
    recursive=yes
    src={{ wagtail_src_path }}/
    dest={{ wagtail_base_dir }}/
#    rsync_opts:
#      - "--chown='{{wagtail_user}}:{{wagtail_group}}'"
#    group={{wagtail_group}}
#    owner={{wagtail_user}}

- name: ensure file permissions
  file: >
    dest={{ wagtail_base_dir }}
    recurse=yes
    owner={{ wagtail_user }}
    group={{ wagtail_group }}

#
# - name: clone wagtail repository
#   sudo_user: "{{ wagtail_user }}"
#   git: >
#     repo={{ wagtail_repo_url }}
#     version={{ wagtail_version }}
#     dest={{ wagtail_base_dir }}
#     force=yes
#
- name: create other directories
  file: >
    state=directory
    path={{ item.path }}
    owner={{ wagtail_user }} group={{ wagtail_group }} mode={{ item.mode | default('0755') }}
  with_items:
    - { path: "{{ wagtail_base_dir }}/static" }
    - { path: "{{ wagtail_base_dir }}/tmp" }
    - { path: "{{ wagtail_uploads_dir }}", mode: '0750' }
    - { path: "{{ wagtail_conf_dir }}" }
    - { path: "{{ wagtail_logs_dir }}" }

- name: add extras to requirements
  lineinfile: >
    dest={{ wagtail_base_dir }}/requirements/dev.txt
    regexp='^{{ item }}'
    line={{ item }}
  with_items:
    - 'django-celery'

- name: install requirements
  sudo_user: "{{ wagtail_user }}"
  pip: >
    requirements={{ wagtail_base_dir }}/requirements/dev.txt
    virtualenv={{ wagtail_virtenv_dir }}

- name: install bower
  npm: name=bower global=true
